//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestPresent.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotTour
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
        public string Category { get; set; }
        public Nullable<int> AmountPeople { get; set; }
        public string DepartureDay { get; set; }
        public string Food { get; set; }
        public Nullable<int> Period { get; set; }
        public string TourType { get; set; }
        public string Location { get; set; }
        public Nullable<int> HotelId { get; set; }
        public string Name { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
