//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestPresent.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public Nullable<int> ReservationNumber { get; set; }
        public Nullable<int> Period { get; set; }
        public string DepartureDay { get; set; }
        public string FirstName { get; set; }
        public string Price { get; set; }
        public string Food { get; set; }
        public string TourType { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Children { get; set; }
        public string HotelCategory { get; set; }
        public string Country { get; set; }
        public string PastPlace { get; set; }
        public string Finance { get; set; }
        public string Comment { get; set; }
    }
}
